language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - cd backend

script:
  - cargo build --verbose
  - cargo test --verbose

notifications:
  - email: false